### ISSUE TITLE
Nextcloud support

### ISSUE THREAD

**Issue by dlemper** [Garbanzo-recipes/garbanzo#1]
- Save data to Nextcloud (removing database backend)?
- Export Data to Nextcloud?
- Nextcloud sharing...?
- using hidden folders?

missing information:
- Nextcloud API or WebDAV

**Comment by dlemper** [comment]
webdav in browser with current nextcloud not possible due to missing CORS header...

**Comment by sehucke** [comment]
What about using a WebView in an app container?

**Comment by dlemper** [comment]
Not sure.. if it works exactly like a browser, then it will require a CORS header and we have the same problem

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sehucke** [comment]
Ehh... I think you are right. WebView should not work either...

But the CORS issue should affect WebDAV only. CORS can be activated via a `@CORS` decorator for ApiController functions. See https://docs.nextcloud.com/server/13/developer_manual/app/api.html.

The options are:
1. Writing an API add-on for NC >= 13 with CORS enabled.
2. Being limited to a native Android app.

The first option would have some advantages:
1. Domain specific, clean separation of front and backend logic.
2. Better options to handle possible future API changes/incompatibilities (i.e. breaking changes in Nextcloud File API) in major versions of Nextcloud.
3. No limitations on the technology we use to implement the frontend.

Drawbacks:
- None that I am aware of :-)

If we manage to keep the backend simple it would be merely a facade for the Nextcloud File API.
And if it gets more complex I would not want such logic in the frontend anyway. :-)

**Comment by dlemper** [comment]
It‘s probably the best to provide several backends, e.g. nextcloud api, express/koa based backend or simply IndexedDB (single user using only a browser).

The backend should be configurable in the settings.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sehucke** [comment]
Exactly what I thought of!

We should separate it as follows: a Garbanzo user can have one or multiple accounts where each has a distinct backend. Each account can hold arbitrary cookbooks with recipes in them. Very similar to the Nextcloud app (with cookbooks and recipes instead of folders and files, of course).

Furthermore, the chosen backend is likely to have an impact on the available feature set (e.g. shared cookbooks). We should keep that in mind.

Am 21. August 2018 23:39:46 MESZ schrieb Daniel Lemper <notifications@github.com>:

**Comment by dlemper** [comment]
I added a ticket, that we can use Github repos (private or public) to store our data.
This is quickly implemented and may be an interesting alternative, as it supports versioning from the beginning.
