### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by dlemper** [Garbanzo-recipes/garbanzo#4]
- [ ] List of recipes
- [ ] Recipes in recipes (pizza contains of the ground and the tomato sauce, which are two recipes indeed)
- [ ] Recipe
  - [ ] Material list (to buy)
  - [ ] List of parts you need (tools)
  - [ ] Step by step list, which can contain timers etc.
- [ ] Shopping list (contains materials from recipes you want to cook)
- [ ] Calendar (appoint meals you want to cook to days in a week for example)

**Comment by dlemper** [comment]
Did I miss something?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sehucke** [comment]
Indeed you did. ;-P

- [ ] Recipe overview (before you get to the step-by-step guide)
- [ ] Collections of recipes a.k.a. Cookbooks
- [ ] Sharing of Cookbooks

And there are a bunch of more "sub-level" features coming to mind...
- [ ] Tagging of recipes
- [ ] Favorite recipes
- [ ] Rating recipes
- [ ] Append files (e.g. the source pdf)
- [ ] OCR import of recipes
- [ ] Import recipes from other sources (maybe by utilizing the Android sharing feature)

**Comment by dlemper** [comment]
I‘ll create a features.md with the content from above and link it in the readme.md. Then we can update it every time we added one of these features within git

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sehucke** [comment]
Nice one! Approved... with some additions!

I got a project board for testing purposes up and running. Please let me know if you think it is suitable for our project.

**Comment by dlemper** [comment]
I converted the FEATURES file into own tickets; that will make the process easier and we can use github projects
